### ISSUE TITLE
Specifying Adapter

### ISSUE THREAD

**Issue by sci345** [usadellab/Trimmomatic#14]
Hello! I am suing Trimmomatic for the first time. I aim to use this on pair end reads. The adapters I wish to trim are illumina TruSeq single index adapters with the sequence below:

Read 1
AGATCGGAAGAGCACACGTCTGAACTCCAGTCA

Read 2
AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT

I notice these sequences are different than the ones provided in Trimmomatic (TruSeq 2 and TrueSeq3). How can I create a file to feed these adapter sequences to Trimmomatic? 

I've read the nicely detailed TrimmomaticManual_V0.32.pdf, section "Making custom clipping files" but I'm still confused as to how to specifically format this file since I see the TruSeq2 and 3 files that Trimmomatic uses have more than just the sequences to read 1 and read 2. 

Apologies for the very basic question. I greatly appreciate your help!

**Comment by TonyBolger** [comment]
These are actually almost the same sequences, just swapped and reverse-complemented (and the first base trimmed)

From the TruSeq3-PE.fa, we have: 
>PrefixPE/1
TACACTCTTTCCCTACACGACGCTCTTCCGATCT
>PrefixPE/2
GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT

Your 'Read 2' sequence, AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT is 'PrefixPE/1', without the first base, and reverse complemented), while your 'Read 1' sequence AGATCGGAAGAGCACACGTCTGAACTCCAGTCA, is 'PrefixPE/2', without the first base and reverse-complemented. 
                                                                                        
There is a difference in terminology - it is common to use the label 'read 1 adapter' for the adapter which will appear in towards the end of read 1, while for trimmomatic, the PrefixPE/1 adapter is the adapter 'before' read 1 (it will be seen in reverse-complement in read 2), and vice versa for Prefix/2. These 'prefix' adapters are matched with a more sensitive and efficient algorithm than others e.g. custom primer sequences. 

Incidentally, the first base will probably be trimmed off each of these PrefixPE sequences in the next release, since the common sequence of all adapters has become shorter in some of the high-throughput kits.
